name: Deploy Next.js App to GitHub Pages
description: Deploys the Next.js App to GitHub Pages
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm clean-install

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: github-pages
          path: out
  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
